theme: jekyll-theme-architect
show_downloads: true
github:
  zip_url: https://github.com/ahtyamovdanil/FatExplorer/releases/download/0.25/FatExplorer_v0.25_win64.zip
  tar_url: https://github.com/ahtyamovdanil/FatExplorer/releases/download/0.25/FatExplorer_v0.25_win64.tar
