theme: jekyll-theme-architect
show_downloads: true
github:
  zip_url: https://github.com/ahtyamovdanil/FatExplorer/releases/download/0.3/FatExplorer_v0.3_win64.zip
  tar_url: https://github.com/ahtyamovdanil/FatExplorer/releases/download/0.3/FatExplorer_v0.3_win64.tar
