theme: jekyll-theme-architect
show_downloads: true
```yml
github:
  zip_url: https://github.com/ahtyamovdanil/FatExplorer/archive/0.2.zip
  tar_url: https://github.com/ahtyamovdanil/FatExplorer/archive/0.2.tar.gz
```
